config/routes.rb
Rails.application.routes.draw do
  # Add your extension routes here
    namespace :admin do
      resources :products do
        resources :productpage_blocks do
          collection do
            post :update_positions
          end
        end
      end
    end
end

app/models/product_decorator.rb
Product.class_eval do
  has_many :productpage_blocks,
  :order => 'productpage_blocks.position ASC'
end

app/models/productpage_block.rb
class ProductpageBlock < ActiveRecord::Base
  belongs_to :product
  validates_presence_of :name
  validates_uniqueness_of :name, :scope => [:product_id]
  validate :no_attachement_errors
  has_attached_file :image,
                    :styles => { :mini => '48x48>', :large => '940x940>' },
                    :default_style => :original,
                    :url => "/assets/products/:id/productpage_blocks/:style/:basename.:extension",
                    :path => ":rails_root/public/assets/products/:id/productpage_blocks/:style/:basename.:extension"
  has_attached_file :popup,
                    :styles => { :mini => '48x48>', :standard => '800x800>', :large => '940x940>'},
                    :default_style => :standard,
                    :url => "/assets/products/:id/productpage_blocks/popup/:style/:basename.:extension",
                    :path => ":rails_root/public/assets/products/:id/productpage_blocks/popup/:style/:basename.:extension"
  acts_as_list

  # save the w,h of the original image (from which others can be calculated)
  # we need to look at the write-queue for images which have not been saved yet
#  after_post_process :find_dimensions

  def find_dimensions
    temporary = image.queued_for_write[:original]
    filename = temporary.path unless temporary.nil?
    filename = attachment.path if filename.blank?
    geometry = Paperclip::Geometry.from_file(filename)
    self.image_width  = geometry.width
    self.image_height = geometry.height
  end

  # if there are errors from the plugin, then add a more meaningful message
  def no_attachement_errors
    unless image.errors.empty?
      # uncomment this to get rid of the less-than-useful interrim messages
      # errors.clear
      errors.add :image, "Paperclip returned errors for file '#{image_file_name}' - check ImageMagick installation or image source file."
      false
    end
  end
end

app/controllers/admin/productpage_blocks_controller.rb
class Admin::ProductpageBlocksController < Admin::ResourceController
  before_filter :load_data
  create.before :set_product
  update.before :set_product

  def update_positions
    params[:positions].each do |id, index|
      ProductpageBlock.update_all(['position=?', index], ['id=?', id])
    end

    respond_to do |format|
      format.js  { render :text => 'Ok' }
    end
  end

  private
  
  def location_after_save
    admin_product_productpage_blocks_url(@product)
  end

  def load_data
    @product = Product.find_by_permalink(params[:product_id])
  end

  def set_product
    @productpage_block.product = @product
  end
end

app/helpers/productpage_blocks_helper.rb
module ProductpageBlocksHelper
end

app/views/admin/productpage_blocks/_form.html.erb
<tr>
  <td><%= t("name") %>:</td>
  <td><%= f.text_field :name, :class => 'fullwidth name' %></td>
</tr>
<tr>
  <td><%= t("width") %>:</td>
  <td><%= f.text_field :width, :class => 'fullwidth name' %></td>
</tr>
<tr>
  <td><%= t("height") %>:</td>
  <td><%= f.text_field :height, :class => 'fullwidth name' %></td>
</tr>
<tr>
  <td><%= t("title") %>:</td>
  <td><%= f.text_field :title, :class => 'fullwidth name' %></td>
</tr>
<tr>
  <td><%= t("html") %>:</td>
  <td><%= f.text_area :html %></td>
</tr>
<tr>
  <td><%= t("filename") %>:</td>
  <td><%= f.file_field :image %></td>
</tr>
<tr>
  <td><%= t("popup_image") %>:</td>
  <td><%= f.file_field :popup %></td>
</tr>

app/views/admin/productpage_blocks/edit.html.erb
<%= render :partial => 'admin/shared/product_sub_menu' %>

<%= render :partial => 'admin/shared/product_tabs', :locals => {:current => "Images"} %>

<%= render "shared/error_messages", :target => @image %>

<%= form_for(:productpage_block, :url => admin_product_productpage_block_url(@product), :html => { :method => :put, :multipart => true }) do |f| %>
  <table class="basic-table">
    <tr>
      <td><%= t("thumbnail") %>:</td>
      <td><%= link_to(image_tag(@productpage_block.image.url(:mini)), @productpage_block.image.url(:product)) %></td>
    </tr>
    <%= render :partial => "form", :locals => { :f => f } %>
  </table>
  <p class="form-buttons">
    <%= button t("update") %>
    <%= t('or') %> <%= link_to t("cancel"), admin_product_productpage_blocks_url(@product), :id => "cancel_link" %>
  </p>
<% end %>

app/views/admin/productpage_blocks/index.html.erb
<%= render :partial => 'admin/shared/product_sub_menu' %>

<%= render :partial => 'admin/shared/product_tabs', :locals => {:current => "Productpage Blocks"} %>

<table class="index sortable">
  <tr>
    <th><%= t("name") %></th>
  </tr>

  <% @product.productpage_blocks.each do |productpage_block| %>
    <tr id="<%= dom_id(productpage_block) %>">
      <td>
        <span class="handle"></span>
        <% if productpage_block.image.file? %>
        	<%= link_to(image_tag(productpage_block.image.url(:mini)), productpage_block.image.url) %>
        <% end %>
      </td>
      <td><%= productpage_block.name %></td>
      <td class="actions">
        <%= link_to_with_icon('edit', t("edit"), edit_admin_product_productpage_block_url(@product, productpage_block), :class => 'edit') %>
        &nbsp;
        <%= link_to_delete productpage_block, {:url => admin_product_productpage_block_url(@product, productpage_block) }%>
      </td>
    </tr>
  <% end %>
</table>

<div id="productpage_block"></div>
<br/>
<p>
    <%= link_to icon('add') + ' ' + t("new_productpage_block"), new_admin_product_productpage_block_url(@product), :id => "new_productpage_block_link" %>
</p>

app/views/admin/productpage_blocks/new.html.erb
<h4><%= t("new_productpage_block") %></h4>
<%= form_for(:productpage_block, :url => { :controller => 'productpage_blocks', :action => 'create' }, :html => { :multipart => true }) do |form| %>
  <table class="basic-table">
    <%= render :partial => "form", :locals => { :f => form } %>
  </table>
  <p class="form-buttons">
    <%= button t("update") %>
    <%= t('or') %> <%= link_to t("cancel"), "#", :id => "cancel_link" %>
  </p>
<% end %>


<script type="text/javascript">    
  jQuery('#cancel_link').click(function (event) { 
    jQuery('#new_productpage_block_link').show();
    jQuery('#productpage_block').html('');
  });  
 
</script>

 
 

app/views/shared/_productpage_blocks_product_tabs.erb
      <li<%== ' class="active"' if current == "Productpage Blocks" %>>
        <%= link_to t("productpage_blocks"),  admin_product_productpage_blocks_url(@product)  %>
      </li>